### ISSUE TITLE
The ability to read and write gzip-compressed tags

### ISSUE THREAD

**Issue by ljfa-ag** [ljfa-ag/libnbtplusplus#6]
For now libraries like Boost::Iostreams or Gzstream can be used for that purpose.

**Comment by ljfa-ag** [comment]
Not sure if that really falls into this library's scope...I think letting external libraries handle that part is the best option

**Comment by peterix** [comment]
Yes... I used a tiny wrapper based on just zlib for this.

See:
https://github.com/MultiMC/MultiMC5/blob/develop/logic/GZip.cpp

Writing would be about as long too.

**Comment by ljfa-ag** [comment]
Okay I see. But I guess it can be useful for other things as well.

**Comment by ljfa-ag** [comment]
That can be considered done now, but maybe there should be some more convenience functions for that
