### ISSUE TITLE
Incorporate changes done in a manual fork

### ISSUE THREAD

**Issue by peterix** [ljfa-ag/libnbtplusplus#7]
Hello, I started using this library in MultiMC, but had to make some changes:
* Make it a shared library instead of a static one (because of LGPL)
* Fix build on OSX and Windows because of the above
* Make the build system a bit more adapted to MultiMC integration

I'll try to get it into a decent repo again so you can use it.

See tracking issue on my end:
https://github.com/MultiMC/MultiMC5/issues/1229

**Comment by ljfa-ag** [comment]
Oh I see, I was not aware that static linking is a problem with the LGPL.
Anyway, glad to see that it finds some use.

**Comment by ljfa-ag** [comment]
I don't think I want to have all these "NBT___EXPORT" in the code. If that is necessary for a shared library than I don't want to make it the default.

**Comment by peterix** [comment]
Ideally, let me clean up what I did. I'll make a normal PR.
